# Generated by Django 3.0.5 on 2020-04-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200427_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
