# Generated by Django 3.0.5 on 2020-05-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('craiglist_bad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
    ]
